name: Python Project Security Workflow

on:
  push:
    branches:
      - main

jobs:
  security-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install CycloneDX
      run: |
        pip install cyclonedx-bom

    - name: Generate SBOM
      run: |
        cyclonedx-py environment -o bom.xml

    - name: Install Safety
      run: |
        pip install safety

    - name: Run Safety Check
      run: |
        safety check -r requirements.txt --full-report

    - name: Upload SBOM as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: SBOM
        path: bom.xml
