name: Python Project SBOM Generation and Analysis

on:
  push:
    branches:
      - main

jobs:
  build-and-analyse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask
        pip install cyclonedx-bom

    - name: Generate SBOM
      run: cyclonedx-py environment -o bom.xml

    - name: Confirm requirements.txt presence
      run: |
        ls -la
        cat requirements.txt

    - name: Download OWASP Dependency-Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip -O dependency-check.zip
        unzip dependency-check.zip

    - name: Run OWASP Dependency-Check
      run: |
        ./dependency-check/bin/dependency-check.sh --project "Flask Hello World" --scan ./requirements.txt --out . --format HTML

    - name: Upload SBOM as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: SBOM
        path: bom.xml

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v2
      with:
        name: Dependency-Check-Report
        path: dependency-check-report.html
